// Copyright 2017-2021 npptesttypes authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: 'npptesttypes', version: '1.0.7' };
